### ISSUE TITLE
Support Tailwind CSS 4

### ISSUE THREAD

**Issue by zwying0814** [stefan-karger/solid-ui#166]
Tailwind CSS 4 has been released, and it is hoped that it will support Tailwind CSS 4.

**Comment by Bersaelor** [comment]
Which means at the moment, the {installation docs](https://www.solid-ui.com/docs/installation/solid-start) aren't working, because the docs say:
```bash
npm init solid@latest
Which template would you like to use? with-tailwindcss
```
which means that the solid template will install tailwind 4.0.5 ( https://github.com/solidjs/templates/blob/main/js-tailwindcss/package.json#L14 )

**Comment by sparklog** [comment]
solid-ui is does not work after updated the solidstart to 1.1 , even if  I changed the dependencies version of tailwind to 3.4.17

**Comment by carere** [comment]
Hello all, while wainting for Tailwind V4 support, here is my functional setup for Solid-UI:
```ts
// app.config.ts (solid-start) or adapt it for vite.config.ts
import { defineConfig } from "@solidjs/start/config";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  ssr: false,
  vite: {
    plugins: [
      tsconfigPaths(),
      tailwindcss(),
    ],
  },
});
```
```css
@import "tailwindcss";

@plugin 'tailwindcss-animate';
@plugin '@kobalte/tailwindcss';

@custom-variant dark (.dark &,[data-kb-theme="dark"] &);

@layer base {
  :root {
    --color-background: hsl(0 0% 100%);
    --color-foreground: hsl(240 10% 3.9%);

    --color-muted: hsl(240 4.8% 95.9%);
    --color-muted-foreground: hsl(240 3.8% 46.1%);

    --color-popover: hsl(0 0% 100%);
    --color-popover-foreground: hsl(240 10% 3.9%);

    --color-border: hsl(240 5.9% 90%);
    --color-input: hsl(240 5.9% 90%);

    --color-card: hsl(0 0% 100%);
    --color-card-foreground: hsl(240 10% 3.9%);

    --color-primary: hsl(240 5.9% 10%);
    --color-primary-foreground: hsl(0 0% 98%);

    --color-secondary: hsl(240 4.8% 95.9%);
    --color-secondary-foreground: hsl(240 5.9% 10%);

    --color-accent: hsl(240 4.8% 95.9%);
    --color-accent-foreground: hsl(240 5.9% 10%);

    --color-destructive: hsl(0 84.2% 60.2%);
    --color-destructive-foreground: hsl(0 0% 98%);

    --color-info: hsl(204 94% 94%);
    --color-info-foreground: hsl(199 89% 48%);

    --color-success: hsl(149 80% 90%);
    --color-success-foreground: hsl(160 84% 39%);

    --color-warning: hsl(48 96% 89%);
    --color-warning-foreground: hsl(25 95% 53%);

    --color-error: hsl(0 93% 94%);
    --color-error-foreground: hsl(0 84% 60%);

    --color-ring: hsl(240 5.9% 10%);
  }

  .dark,
  [data-kb-theme="dark"] {
    --color-background: hsl(240 10% 3.9%);
    --color-foreground: hsl(0 0% 98%);

    --color-muted: hsl(240 3.7% 15.9%);
    --color-muted-foreground: hsl(240 5% 64.9%);

    --color-accent: hsl(240 3.7% 15.9%);
    --color-accent-foreground: hsl(0 0% 98%);

    --color-popover: hsl(240 10% 3.9%);
    --color-popover-foreground: hsl(0 0% 98%);

    --color-border: hsl(240 3.7% 15.9%);
    --color-input: hsl(240 3.7% 15.9%);

    --color-card: hsl(240 10% 3.9%);
    --color-card-foreground: hsl(0 0% 98%);

    --color-primary: hsl(0 0% 98%);
    --color-primary-foreground: hsl(240 5.9% 10%);

    --color-secondary: hsl(240 3.7% 15.9%);
    --color-secondary-foreground: hsl(0 0% 98%);

    --color-destructive: hsl(0 62.8% 30.6%);
    --color-destructive-foreground: hsl(0 0% 98%);

    --color-info: hsl(204 94% 94%);
    --color-info-foreground: hsl(199 89% 48%);

    --color-success: hsl(149 80% 90%);
    --color-success-foreground: hsl(160 84% 39%);

    --color-warning: hsl(48 96% 89%);
    --color-warning-foreground: hsl(25 95% 53%);

    --color-error: hsl(0 93% 94%);
    --color-error-foreground: hsl(0 84% 60%);

    --color-ring: hsl(240 4.9% 83.9%);
  }

  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }

  @media (max-width: 640px) {
    .container {
      @apply px-4;
    }
  }

  ::-webkit-scrollbar {
    width: 16px;
  }

  ::-webkit-scrollbar-thumb {
    border-radius: 9999px;
    border: 4px solid transparent;
    background-clip: content-box;
    @apply bg-accent;
  }

  ::-webkit-scrollbar-corner {
    display: none;
  }

  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

@theme {
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-background: var(--background);
  --color-foreground: var(--foreground);

  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);

  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);

  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);

  --color-info: var(--info);
  --color-info-foreground: var(--info-foreground);

  --color-success: var(--success);
  --color-success-foreground: var(--success-foreground);

  --color-warning: var(--warning);
  --color-warning-foreground: var(--warning-foreground);

  --color-error: var(--error);
  --color-error-foreground: var(--error-foreground);

  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);

  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);

  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);

  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);

  --radius: 0.5rem;
  --radius-xl: calc(var(--radius) + 4px);
  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--kb-accordion-content-height);
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--kb-accordion-content-height);
    }
    to {
      height: 0;
    }
  }

  @keyframes content-show {
    from {
      opacity: 0;
      transform: scale(0.96);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  @keyframes content-hide {
    from {
      opacity: 1;
      transform: scale(1);
    }
    to {
      opacity: 0;
      transform: scale(0.96);
    }
  }

  @keyframes caret-blink {
    0%,
    70%,
    100% {
      opacity: 1;
    }
    20%,
    50% {
      opacity: 0;
    }
  }

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;
  --animate-content-show: content-show 0.2s ease-out;
  --animate-content-hide: content-hide 0.2s ease-out;
  --animate-caret-blink: caret-blink 1.25s ease-out infinite;
}

@utility container {
  margin-inline: auto;
  padding-inline: 2rem;
  @media (width >= --theme(--breakpoint-sm)) {
    max-width: none;
  }
  @media (width >= 1400px) {
    max-width: 1400px;
  }
}

@utility step {
  counter-increment: step;

  &:before {
    @apply absolute w-9 h-9 bg-muted rounded-full font-mono font-medium text-center text-base inline-flex items-center justify-center -indent-px border-4 border-background;
    @apply ml-[-50px] mt-[-4px];
    content: counter(step);
  }
}
```
I hope for those who are blocked will be happy to work with this wonderful lib & Tailwind 4 :)

**Comment by chasingtheflow** [comment]
Thanks @carere, following these steps more-or-less worked for me, though I did need to install kobalte/tailwindcss with `npm install -D @kobalte/tailwindcss --legacy-peer-deps` as I did not have it in the project already.

**Comment by sparklog** [comment]
thanks!

**Comment by stefan-karger** [comment]
thanks for all the feedback :)
for now v4 support is not planned since I only have limited time due to our newborn and I want so solve all the issues first :)

but once solid 2 beta hits I have to redo all the components anyway and that's when I want to add v4 support 

but if someone has some time at hand and wants to provide a PR for the cli feel free to do it! <3
this would help so much especially most of the stuff can be ported from shadcn :)

**Comment by carere** [comment]
@stefan-karger I can help you on this one, do you have an exhaustive list to add support for tailwind V4 to the CLI ?

**Comment by carere** [comment]
The tailwind config I shared is already working with v4 and SolidUi, since it is what I use on my own project :)
So i'll use this as a base and open a PR :)

**Comment by LB-sx** [comment]
The only bit that needs to be addressed to have the current components working with Tailwind v4 is the replacement of "tailwindcss-animate", for the rest the tailwind upgrade script is doing all the work

**Comment by LB-sx** [comment]
I have not tried yet, but this: [https://github.com/Wombosvideo/tailwindcss-animate-v4](https://github.com/Wombosvideo/tailwindcss-animate-v4) may probably solve the tailwind-animate issue

**Comment by stefan-karger** [comment]
> The tailwind config I shared is already working with v4 and SolidUi, since it is what I use on my own project :) So i'll use this as a base and open a PR :)

could you still have a look at the guide that shadcn provides?
the setup you have works fine but he proposes a few changes that look like it makes the css file more readable :)

https://ui.shadcn.com/docs/tailwind-v4#2-update-your-css-variables

**Comment by stefan-karger** [comment]
small update:
shadcn slightly changed the colors
https://github.com/shadcn-ui/ui/blob/8d5d62f9d996204f515e2001856ca8aab48fca1a/apps/www/public/r/colors/zinc.json#L100-L167

**Comment by carere** [comment]
@stefan-karger Hello :)

I plan on copying the entire CLI from ShadCn and replace the existing one in Soilid-UI. Is that ok with you ?? That way we will have every feature from ShadCN since it's the most advanced CLI actually amongs all projects (yours, shadcn-solid, shadcn-ui, etc)

**Comment by stefan-karger** [comment]
> [@stefan-karger](https://github.com/stefan-karger) Hello :)
> 
> I plan on copying the entire CLI from ShadCn and replace the existing one in Soilid-UI. Is that ok with you ?? That way we will have every feature from ShadCN since it's the most advanced CLI actually amongs all projects (yours, shadcn-solid, shadcn-ui, etc)

that would be what I would do next so feel free to start a pr :)

**Comment by carere** [comment]
Hello all 😄

Here is [the PR](https://github.com/stefan-karger/solid-ui/pull/185) for Tailwind V4 migration (and Shadcn registry).

For the most impatients, you can check the CSS files used in this PR for the SolidUI website, it's updated to Tailwind V4, with OKCHL colors & it is based on Shadcn version.

```css
@import "tailwindcss";
@import "tw-animate-css";
@plugin "@kobalte/tailwindcss";

@custom-variant dark (&:where(.dark, .dark *, [data-kb-theme=dark], [data-kb-theme=dark] *));

:root {
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --destructive-foreground: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --radius: 0.5rem;
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark,
  [data-kb-theme="dark"] {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.145 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.145 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.985 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.396 0.141 25.723);
  --destructive-foreground: oklch(0.637 0.237 25.331);
  --border: oklch(0.269 0 0);
  --input: oklch(0.269 0 0);
  --ring: oklch(0.439 0 0);
  --radius: 0.5rem;
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(0.269 0 0);
  --sidebar-ring: oklch(0.439 0 0);
}

@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);

  --radius: 0.5rem;
  --radius-xl: calc(var(--radius) + 4px);
  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);

  --font-*: initial;
  --font-sans: "Geist Sans", sans-serif;
  --font-mono: "Geist Mono", monospace;

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--kb-accordion-content-height);
    }
  }

  @keyframes accordion-up {
    from {
      height: var(--kb-accordion-content-height);
    }
    to {
      height: 0;
    }
  }

  @keyframes content-show {
    from {
      opacity: 0;
      transform: scale(0.96);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  @keyframes content-hide {
    from {
      opacity: 1;
      transform: scale(1);
    }
    to {
      opacity: 0;
      transform: scale(0.96);
    }
  }

  @keyframes caret-blink {
    0%,
    70%,
    100% {
      opacity: 1;
    }
    20%,
    50% {
      opacity: 0;
    }
  }

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;
  --animate-content-show: content-show 0.2s ease-out;
  --animate-content-hide: content-hide 0.2s ease-out;
  --animate-caret-blink: caret-blink 1.25s ease-out infinite;
}

@utility container {
  @apply px-8;
  @media (width >= --theme(--breakpoint-sm)) {
    @apply max-w-none;
  }
  @media (max-width: 640px) {
    @apply px-4;
  }
}

@utility step {
  counter-increment: step;

  &:before {
    @apply absolute w-9 h-9 bg-muted rounded-full font-mono font-medium text-center text-base inline-flex items-center justify-center -indent-px border-4 border-background;
    @apply ml-[-50px] mt-[-4px];
    content: counter(step);
  }
}

@layer base {
  @font-face {
    font-family: "Geist Sans";
    src: url("/fonts/Geist.woff2") format("woff2");
    font-display: swap;
  }

  @font-face {
    font-family: "Geist Mono";
    src: url("/fonts/GeistMono.woff2") format("woff2");
    font-display: swap;
  }

  * {
    @apply border-border outline-ring/50;
  }

  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }

  /**
   * Scrollbar
   */

  ::-webkit-scrollbar {
    width: 16px;
  }
  
  ::-webkit-scrollbar-thumb {
    border-radius: 9999px;
    border: 4px solid transparent;
    background-clip: content-box;
    @apply bg-accent;
  }
  
  ::-webkit-scrollbar-corner {
    display: none;
  }

  /**
   * Corvu Resizable Panel
   */

  [data-corvu-resizable-panel]:has(+ [data-corvu-resizable-handle][data-dragging]) iframe {
    pointer-events: none;
  }

  /**
   * MDX Rehype
   */

  [data-rehype-pretty-code-fragment] {
    @apply relative;
  }
  
  [data-rehype-pretty-code-fragment] [data-highlighted-line] {
    @apply bg-white/10;
  }
  
  [data-rehype-pretty-code-fragment] [data-line] {
    @apply px-4 min-h-[1rem] py-0.5 w-full inline-block;
  }
  
  [data-rehype-pretty-code-fragment] code {
    @apply grid min-w-full break-words rounded-none border-0 bg-transparent p-0;
    counter-reset: line;
    box-decoration-break: clone;
  }
  
  [data-rehype-pretty-code-fragment] [data-line-numbers] [data-line] {
    @apply px-2;
  }
  
  [data-rehype-pretty-code-fragment] [data-line-numbers] > [data-line]::before {
    @apply text-zinc-50/40 text-xs;
    counter-increment: line;
    content: counter(line);
    display: inline-block;
    width: 1.8rem;
    margin-right: 1.4rem;
    text-align: right;
  }
  
  [data-rehype-pretty-code-title] {
    @apply mt-2 pt-6 px-4 text-sm font-medium;
  }
  
  [data-rehype-pretty-code-title] + div > pre {
    @apply mt-2;
  }
}
```
I left a checklist on the PR, in order for you to follow the progression of the migration 😉

PS: You should remove what you don't need from this CSS file or simply use the one from Shadcn repository.
