### ISSUE TITLE
Sidebar css not working

### ISSUE THREAD

**Issue by maxomatic458** [stefan-karger/solid-ui#175]
Im trying to use the sidebar component, but for some reason the css is not working.
I did follow those steps: https://www.solid-ui.com/docs/components/sidebar

app.css
```css
@layer base {
    :root {
        --color-background: hsl(0, 0%, 100%);
        --color-foreground: hsl(240 10% 3.9%);

        --color-muted: hsl(240 4.8% 95.9%);
        --color-muted-foreground: hsl(240 3.8% 46.1%);

        --color-popover: hsl(0 0% 100%);
        --color-popover-foreground: hsl(240 10% 3.9%);

        --color-border: hsl(240 5.9% 90%);
        --color-input: hsl(240 5.9% 90%);

        --color-card: hsl(0 0% 100%);
        --color-card-foreground: hsl(240 10% 3.9%);

        --color-primary: hsl(240 5.9% 10%);
        --color-primary-foreground: hsl(0 0% 98%);

        --color-secondary: hsl(240 4.8% 95.9%);
        --color-secondary-foreground: hsl(240 5.9% 10%);

        --color-accent: hsl(240 4.8% 95.9%);
        --color-accent-foreground: hsl(240 5.9% 10%);

        --color-destructive: hsl(0 84.2% 60.2%);
        --color-destructive-foreground: hsl(0 0% 98%);

        --color-info: hsl(204 94% 94%);
        --color-info-foreground: hsl(199 89% 48%);

        --color-success: hsl(149 80% 90%);
        --color-success-foreground: hsl(160 84% 39%);

        --color-warning: hsl(48 96% 89%);
        --color-warning-foreground: hsl(25 95% 53%);

        --color-error: hsl(0 93% 94%);
        --color-error-foreground: hsl(0 84% 60%);

        --color-ring: hsl(240 5.9% 10%);

        --sidebar-background: 0 84% 60%;
        --sidebar-foreground: 240 5.3% 26.1%;
        --sidebar-primary: 240 5.9% 10%;
        --sidebar-primary-foreground: 0 0% 98%;
        --sidebar-accent: 240 4.8% 95.9%;
        --sidebar-accent-foreground: 240 5.9% 10%;
        --sidebar-border: 220 13% 91%;
        --sidebar-ring: 217.2 91.2% 59.8%;

    }
```

tailwind.config.cjs (i already tried putting the sidebar in different places, as the docs dont really show where exactly to put it).
```.cjs

export default {
    darkMode: ['variant', ['.dark &', '[data-kb-theme="dark"] &']],
    content: ['./src/**/*.{ts,tsx}'],
    prefix: '',
    theme: {
        sidebar: {
            DEFAULT: 'hsl(var(--sidebar-background))',
            foreground: 'hsl(var(--sidebar-foreground))',
            primary: 'hsl(var(--sidebar-primary))',
            'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
            accent: 'hsl(var(--sidebar-accent))',
            'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
            border: 'hsl(var(--sidebar-border))',
            ring: 'hsl(var(--sidebar-ring))',
        },
...
```

AccountSidebar.tsx
```tsx

const items = [
    {
        title: "Settings",
        url: "/account/settings",
    },
    {
        title: "Billing",
        url: "/account/billing",
    },
    {
        title: "Profile",
        url: "/account/profile",
    },
]

export default function AccountSideBar() {
    return (

        <>
        <Sidebar class="w-30">
            <SidebarContent>
                <SidebarGroup>
                    <SidebarGroupLabel>Account</SidebarGroupLabel>
                    <SidebarGroupContent>
                        <SidebarMenu>
                            <For each={items}>
                                {(item) => (
                                    <SidebarMenuItem>
                                        <SidebarMenuButton as="a" href={item.url}>
                                            {item.title}
                                        </SidebarMenuButton>
                                    </SidebarMenuItem>
                                )}
                            </For>
                        </SidebarMenu>
                    </SidebarGroupContent>
                </SidebarGroup>
            </SidebarContent>
        </Sidebar>
        </>
    )
}
```

account.tsx
```tsx
export default function Account() {
    return (
        <SidebarProvider>
            <AccountSideBar />
            <div>
                <h1>Account Page</h1>
            </div>
        </SidebarProvider>
    )
}
```

No matter what i change in the css (or even in the tailwind.config.cjs directly), the look does not change:

![Image](https://github.com/user-attachments/assets/911c4762-470d-450d-b782-8498c77cda57)

Note: i did follow the steps in #166 to get tailwind 4 to work
